/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2025-10-07 05:35:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import negocio.Usuario;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("negocio.Usuario");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    Usuario usuario = (Usuario) session.getAttribute("usuario");
    if (usuario == null) {
        response.sendRedirect("login.jsp");
        return;
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Menú Principal</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            margin: 0;\n");
      out.write("            font-family: \"Segoe UI\", sans-serif;\n");
      out.write("            background-color: #f8f9fa;\n");
      out.write("            display: flex;\n");
      out.write("            height: 100vh;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Sidebar */\n");
      out.write("        .sidebar {\n");
      out.write("            width: 250px;\n");
      out.write("            background: linear-gradient(180deg, #5A0000, #B22222);\n");
      out.write("            color: white;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            padding: 1rem;\n");
      out.write("            transition: width 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar.collapsed {\n");
      out.write("            width: 80px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-header {\n");
      out.write("            font-size: 1.3rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar.collapsed .sidebar-header span {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .toggle-btn {\n");
      out.write("            background: none;\n");
      out.write("            border: none;\n");
      out.write("            color: white;\n");
      out.write("            font-size: 1.3rem;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Menu links */\n");
      out.write("        .menu-link {\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 10px;\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            margin-bottom: 0.4rem;\n");
      out.write("            transition: background-color 0.3s, color 0.3s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .menu-link i {\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .menu-link:hover {\n");
      out.write("            background-color: rgba(255, 255, 255, 0.15);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* 🔹 Enlace activo */\n");
      out.write("        .menu-link.active {\n");
      out.write("            background: linear-gradient(90deg, #B22222, #8B0000);\n");
      out.write("            color: #FFD700 !important;\n");
      out.write("            font-weight: 600;\n");
      out.write("            box-shadow: 0 0 8px rgba(255, 215, 0, 0.6);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .menu-link.active i {\n");
      out.write("            color: #fff !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar.collapsed .menu-link span {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar.collapsed .menu-link {\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Logout */\n");
      out.write("        .logout {\n");
      out.write("            margin-top: auto;\n");
      out.write("            background-color: rgba(255, 255, 255, 0.1);\n");
      out.write("            color: #ffdddd;\n");
      out.write("            transition: background-color 0.3s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logout:hover {\n");
      out.write("            background-color: rgba(255, 255, 255, 0.25);\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Main content */\n");
      out.write("        .content {\n");
      out.write("            flex-grow: 1;\n");
      out.write("            padding: 1.5rem;\n");
      out.write("            background-color: #f0f2f5;\n");
      out.write("            overflow-y: auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        iframe {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            background: white;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .sidebar {\n");
      out.write("                position: fixed;\n");
      out.write("                z-index: 10;\n");
      out.write("                height: 100%;\n");
      out.write("                transform: translateX(-100%);\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .sidebar.show {\n");
      out.write("                transform: translateX(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- Sidebar -->\n");
      out.write("    <div class=\"sidebar\" id=\"sidebar\">\n");
      out.write("        <div class=\"sidebar-header\">\n");
      out.write("            <span>Menú</span>\n");
      out.write("            <button class=\"toggle-btn\" id=\"toggle-btn\"><i class=\"bi bi-list\"></i></button>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <a href=\"bienvenida.jsp\" target=\"contenido\" class=\"menu-link active\">\n");
      out.write("            <i class=\"bi bi-house\"></i> <span>Inicio</span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"crearCuenta.jsp\" target=\"contenido\" class=\"menu-link\">\n");
      out.write("            <i class=\"bi bi-person-plus\"></i> <span>Crear Cuenta</span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"deposito.jsp\" target=\"contenido\" class=\"menu-link\">\n");
      out.write("            <i class=\"bi bi-cash-coin\"></i> <span>Depósito</span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"consultaCuentas.jsp\" target=\"contenido\" class=\"menu-link\">\n");
      out.write("            <i class=\"bi bi-search\"></i> <span>Consultar Cuentas</span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"movimientos.jsp\" target=\"contenido\" class=\"menu-link\">\n");
      out.write("            <i class=\"bi bi-clock-history\"></i> <span>Movimientos</span>\n");
      out.write("        </a>\n");
      out.write("\n");
      out.write("        <a href=\"login.jsp\" class=\"menu-link logout\">\n");
      out.write("            <i class=\"bi bi-box-arrow-right\"></i> <span>Cerrar Sesión</span>\n");
      out.write("        </a>\n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("\n");
      out.write("    <!-- Contenido principal -->\n");
      out.write("    <div class=\"content\">\n");
      out.write("        <iframe name=\"contenido\" src=\"bienvenida.jsp\"></iframe>\n");
      out.write("        \n");
      out.write("                <!-- Include Timer -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/reutilizables/temporizador.jsp", out, false);
      out.write("\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        // Colapsar/expandir menú\n");
      out.write("        document.getElementById('toggle-btn').addEventListener('click', function() {\n");
      out.write("            document.getElementById('sidebar').classList.toggle('collapsed');\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // Mantener el botón activo\n");
      out.write("        const links = document.querySelectorAll('.menu-link');\n");
      out.write("        links.forEach(link => {\n");
      out.write("            link.addEventListener('click', () => {\n");
      out.write("                links.forEach(l => l.classList.remove('active'));\n");
      out.write("                link.classList.add('active');\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
